services: 
  app:
    build:
      context: .
    ports:
      - "3000:3000"

#docker-compose -f docker-compose-local.yml build
#docker-compose -f docker-compose-local.yml up -d      
#docker-compose -f docker-compose-local.yml down

#docker-compose -f docker-compose-local.yml up --build      
