FROM golang:1.25.4-alpine3.21 AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o gin-api-app .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/gin-api-app .
EXPOSE 8080
CMD ["./gin-api-app"]
